[window]
dimensions = { columns = 81 , lines = 25 }
padding = { x = 4 , y = 2 }
dynamic_padding = true
opacity = 0.7
title = "Alacritty"
dynamic_title = true
blur = true
decorations_theme_variant = "Dark"

[font]
#normal = { family = "CaskaydiaCoveNerdFontMono" , style = "Regular" }
#bold = { family = "CaskaydiaCoveNerdFontMono" , style = "Bold" }
#italic = { family = "CaskaydiaCoveNerdFontMono" , style = "Italic" }
#bold_italic = { family = "CaskaydiaCoveNerdFontMono" , style = "BoldItalic" }

normal = { family = "0xProtoNerdFontMono" , style = "Regular" }
bold = { family = "0xProtoNerdFontMono" , style = "Bold" }
italic = { family = "0xProtoNerdFontMono" , style = "Italic" }
bold_italic = { family = "0xProtoNerdFontMono" , style = "BoldItalic" }

#normal = { family = "" , style = "Regular" }
#bold = { family = "" , style = "Bold" }
#italic = { family = "" , style = "Italic" }
#bold_italic = { family = "" , style = "BoldItalic" }

size = 21